from __future__ import annotations

from typing import Optional, Type, Generator
from pydantic import root_validator, Field

from .base import AbstractOperation, register_operation
from ..apps import AppMetadata
from ..registry import AppRegistry
from ..state import State, Status


__all__ = ("Plan", "AppPlan", "AppsPlan")


@register_operation
class Plan(AbstractOperation):
    """Run multiple operations sequentially."""

    operations: list[AbstractOperation]
    """ The operations to run. """
    name = "plan"

    def create_state(self, **kwargs) -> State:
        kwargs["states"] = []
        state = super().create_state(**kwargs)
        for idx, op in enumerate(self.operations):
            op_state = op.create_state()
            state.states.append(op_state)
        return state

    def validate_state(self, state, recurse=False):
        super().validate_state(state)

        assert len(state.states) == len(self.operations)

        # This arguments avoids double validation on
        # apply/rollback.
        if recurse:
            for idx, op in enumerate(self.operations):
                if len(state.states) <= idx:
                    raise ValueError(f"Missing state for operation `{op}`")
                op.validate_state(state.states[idx])

    def _apply(self, state, **kwargs) -> Generator[State]:
        """
        Execute nested operations.

        On failure, it will rollback the whole current operation before raising
        the exception again. The ``**kwargs`` arguments will be passed down to
        the :py:meth:`rollback` method.

        .. note::

            Since the operation raise once rolled back, parent Plan class will
            will rollback too.

        """
        kwargs["plan"] = self

        for idx, op in enumerate(self.operations):
            try:
                op_state = state.states[idx]
                yield from op.apply(state=op_state, **kwargs)
            except Exception as exc:
                yield state.fail(exc)
                yield from self.rollback(state, op_idx=idx, **kwargs)
                raise

    def _rollback(self, state, op_idx=None, **kwargs) -> Generator[State]:
        """
        Execute rollbacks for nested operations (in reverse order).

        On failure, state will be marked as failed and error is raised.

        :param state: the actual state
        :param op_idx: rollback from to operation (to start)
        """
        kwargs["plan"] = self

        if op_idx:
            ops, states = self.operations[: op_idx + 1], state.states[: op_idx + 1]
        else:
            ops, states = self.operations, state.states

        for op, op_state in zip(reversed(ops), reversed(states)):
            # on failed, calling rollback handles it
            if not op_state.is_any(Status.PENDING, Status.ROLLED_BACK):
                yield from op.rollback(op_state, **kwargs)


@register_operation
class AppPlan(Plan):
    app: AppMetadata
    name = "app_plan"

    def _apply(self, **kwargs):
        kwargs["app"] = self.app
        yield from super()._apply(**kwargs)

    def _rollback(self, **kwargs):
        kwargs["app"] = self.app
        yield from super()._apply(**kwargs)


@register_operation
class AppsPlan(Plan):
    """
    Installation plan for multiple applications.

    The main idea behind AppsPlan is to provide a set of operations that is common
    among different calls. For example, provide a standard workflow for app install
    or update.

    To set applications, you either explicitely set them on an instance
    (:py:meth:`set_apps`), or by loading them by name from the application
    registry (:py:meth:`load_apps`). The latest return a clone of self by default.
    """

    pre_operations: Optional[list[AbstractOperation]] = None
    """ Operations to run before AppPlan ones. """
    post_operations: Optional[list[AbstractOperation]] = None
    """ Operations to run after AppPlan ones. """
    app_operations: Optional[list[AbstractOperation]] = None
    """ Operation to set on each AppPlan. """
    apps: list[AppMetadata] = Field(exclude=True, default_factory=list)
    """ Ordered list of applications, set using :py:meth:`set_apps` or :py:meth:`load_apps` """
    operations: Optional[list[AbstractOperation]] = Field(exclude=True, default_factory=list)
    """ The operations generated by :py:meth:`set_apps`. """

    name = "apps_plan"

    app_plan_class: Type[AppPlan] = AppPlan

    def __init__(self, **kwargs):
        super().__init__(**kwargs)

        if self.pre_operations is None:
            self.pre_operations = []  # type(self).pre_operations or []
        if self.post_operations is None:
            self.post_operations = []  # type(self).post_operations or []

        self.operations = None

    @root_validator(pre=True)
    def validate_forbidden_fields(cls, values):
        """Forbid operations to be provided"""
        if values.get("operations"):
            raise ValueError(
                "You are not allowed to set `operations` on AppsPlan; use `app_plans`, `pre_operations`,"
                "`post_operations` instead"
            )
        if values.get("apps"):
            raise ValueError("You are not allowed to set `apps` on AppsPlan; use `set_apps` or " "`load_apps`.")
        return values

    def set_apps(self, apps):
        self.apps = apps
        self.operations = self.get_operations()

    def get_operations(self):
        return self.pre_operations + [self.get_app_plan(app) for app in self.apps] + self.post_operations

    def get_app_plan(self, app: AppMetadata, **kwargs):
        kwargs["operations"] = self.app_operations or []
        return self.app_plan_class(app=app, **kwargs)

    def load_apps(self, registry: AppRegistry, names: list[str], clone: bool = True) -> AppsPlan:
        """
        Load applications and their dependencies from registry and set them
        on instance.

        When ``clone`` is True (default behavior), the applications are loaded
        into a copy of self instead of modifying instance inplace.
        """
        apps = registry.get_full(names)
        if clone:
            self = self.clone()
        self.set_apps(apps)
        return self
