from __future__ import annotations
from abc import ABC, abstractmethod
from dataclasses import dataclass
from datetime import datetime, timezone
from typing import Any
from uuid import uuid4

from pydantic import BaseModel, Field

from .pydantic import PolymorphicModel
from .registry import DocumentedRegistry, DocumentedClass


__all__ = (
    "CONTEXT_INPUT_REGISTRY",
    "ContextInput",
    "RawContextInputs",
    "ContextInputMap",
    "ContextInputs",
    "Context",
    "RunContext",
)


CONTEXT_INPUT_REGISTRY = DocumentedRegistry()


class ContextInput(PolymorphicModel, DocumentedClass, ABC):
    """
    Input data provided by user and converted into a context class.

    This class shall be registered using ``register`` decorator. The provided
    key is the one used as operation apply/rollback arguments.

    Its :py:meth:`build_context` MUST be provided.

    .. important::

        This object is not aimed as to fully deserialize and handle permissions,
        rather provide a simple layer between context and raw input data.

        For example, it can handle conversion between a store information and the
        actual store instance but you don't wan't user being able to edit file
        though a rest API.

    """

    __registry__ = CONTEXT_INPUT_REGISTRY
    __context_key__: str | None = None
    """
    Override the key used to assign the generated Context as argument name
    of the operations.
    """

    @abstractmethod
    def build_context(self, context_inputs: ContextInputs, **kwargs) -> Context:
        """
        Return the context based on the provided execution specification and
        contexts.

        It is not expected to add the new object into the contexts dict

        :param context_inputs: the calling ContextInputs;
        :param **kwargs: extra initial attributes;
        """
        pass

    @classmethod
    def get_context_key(cls) -> str:
        """Return the key of the context generated by this input."""
        return cls.__context_key__ or cls.__type_id__


RawContextInputs = dict[str, ContextInput | dict[str, Any]]
"""
Raw ContextInput data.

It is normalized by the :py:meth:`ContextInputs.norm_inputs` to provide
"""
ContextInputMap = dict[str, ContextInput]
""" Normalized dict of context inputs as used by :py:class:`ContextInputs`. """


class ContextInputs:
    """
    Handle contexts building using :py:class:`ContextInput`.

    Basically:

        - User provide input data, which are deserialized as ContextInput;
        - The class uses them to build the contexts;
        - Those contexts can then provided as input values to operations;

    The generated contexts' keys map by default to the type id of the ContextInput
    (provided using the ``@register`` decorator). However you can assign
    :py:attr:`ContextInput.__context_key__` to avoid name clashes.

    This assume the distinction between:

        - The ContextInput key: used for building contexts;
        - The Context key: used as final context argument and in :py:meth:`resolve`;
    """

    inputs: RawContextInputs | ContextInputMap = None
    """ ContextInput values.

    It is expected to be raw values at init. The ``__init__`` method will
    ensure they are correctly deserialized to ContextInput.
    """
    contexts: dict[str, Context] = None
    """ Generated contexts """
    registry: DocumentedRegistry = CONTEXT_INPUT_REGISTRY
    """ ContextInput classes registry. """
    key_map: dict[str, str] = None
    """ Mapping from context to input keys. """

    def __init__(
        self,
        inputs: RawContextInputs | None = None,
        contexts: dict[str, Context] | None = None,
        registry: DocumentedRegistry | None = None,
    ):
        self.inputs = inputs and self.norm_inputs(inputs) or {}
        self.contexts = contexts or {}
        if registry is not None:
            self.registry = registry

        self.key_map = {i.get_context_key(): i.__type_id__ for i in self.registry.values()}

    def norm_inputs(self, inputs: RawContextInputs) -> ContextInputMap:
        """
        Ensure inputs are initialized using the right ContextInput class.

        This allows convenient formatting, without having to provide the
        polymorphic serialization format.
        """
        for key, values in inputs.items():
            if isinstance(values, dict):
                input_cls = self.registry.get(key)
                inputs[key] = input_cls.model_validate(values)
        return inputs

    def build(self, reset: bool = False):
        """
        Build all contexts of provided inputs, skipping existing ones.

        :param reset: clear all previous contexts.
        :return contexts.
        """
        if reset:
            self.contexts = {}

        for key, input in self.inputs.items():
            context_key = input.get_context_key()
            if context_key not in self.contexts:
                self.build_context(key)

    def resolve(self, context_key: str) -> Context:
        """
        Get or create context by context key.

        When the user didn't provide any input for generating a context, it
        will raises a ValueError.

        See :py:meth:`build_context` for more information about context creation.
        """
        if context := self.contexts.get(context_key):
            return context

        input_key = self.key_map.get(context_key)
        return self.build_context(input_key)

    def build_context(self, input_key: str) -> Context:
        """
        Build a new context and save it to :py:attr:`contexts`.

        When there is no ContextInput provided in :py:attr:`inputs`, it will try
        to find a corresponding registered one to instanciate the context.

        :yields ValueError: when creating a context for which user has provided no input.
        :yields ValueError: when there is no registered ContextInput class handling the context creation.
        :yields pydantic.ValidationError: when there are missing input value from the user to create the context.
        """
        context_input = self.inputs.get(input_key)
        if not context_input:
            # input not provided by user, instanciate it.
            # pydantic will raise a validation error, if there are missing required
            # fields.
            context_input = self.registry.get(input_key)()
            self.inputs[input_key] = context_input

        context = context_input.build_context(self)
        context_key = context_input.get_context_key()
        self.contexts[context_key] = context
        return context

    def get_context_key(self, input_key) -> str:
        """Return context key for the provided ContextInput one.

        :raises KeyError: no input exists with this key.
        """
        input_cls = self.registry.get(input_key)
        return input_cls.get_context_key()


@dataclass
class Context:
    """Base class for all contexts."""

    pass


class RunContext(BaseModel, Context):
    """
    Running context of operations, provided to the root state of operations.

    Must be serializable as it is assigned to root operation state.
    """

    run_id: str = Field(default_factory=lambda: str(uuid4()))
    """ Run id. """
    started_at: datetime | None = None
    """ Run execution start. """
    finished_at: datetime | None = None
    """ Run execution end. """
    trigger: str = "cli"
    """ What triggered this execution, as cli, api, scheduler,... """
    dry_run: bool = False
    """ Ran in dry run mode. """

    def start(self):
        """Tag context as started."""
        self.started_at = datetime.now(timezone.utc)

    def finish(self):
        """Tag context as finished.

        :raises RuntimeError: when the context hasn't been started first.
        """
        if self.started_at is None:
            raise RuntimeError("You must first call start to finish it.")

        self.finished_at = datetime.now(timezone.utc)
