# Generated by Django 5.2.13 on 2026-06-23 08:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("django_app_1", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="PersonAddress",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("person", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="django_app_1.person")),
            ],
        ),
    ]
